# FiPy Travis Continuous Integration build script
# for Spinodal Decomposition benchmark problems
# Questions/comments to trevor.keller@nist.gov (Trevor Keller)
#
# .travis.yml modified after
#  https://github.com/wd15/extremefill2D/blob/master/.travis.yml

---
language: python

notifications:
  email: false

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -y -n test-environment python=2.7
  - source activate test-environment
  - conda install -q -y -n test-environment numpy scipy sympy
  - pip install scikit-fmm
  - cd $TRAVIS_BUILD_DIR/fipy
  # 2to3 --write .
  - python setup.py install
  - cd $TRAVIS_BUILD_DIR

script:
  - ./run_benchmarks.sh

after_script:
  - for d in {periodic,no-flux,T-shape}; do cat $d/meta.yml; echo; done
