# FiPy Travis Continuous Integration build script
# for Spinodal Decomposition benchmark problems
# Questions/comments to trevor.keller@nist.gov (Trevor Keller)
# Borrowed from https://github.com/guyer/fipy/blob/travisize/.travis.yml
#
#
# inspired by http://conda.pydata.org/docs/travis.html
#
# language: python causes grief on osx
language: generic
os:
   - linux

env:
  - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=pysparse
  # - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=scipy
  # - TRAVIS_PYTHON_VERSION=2.7 MPIRUN= FIPY_SOLVERS=trilinos
  # - TRAVIS_PYTHON_VERSION=2.7 MPIRUN="mpirun -np 2" FIPY_SOLVERS=trilinos
  # - TRAVIS_PYTHON_VERSION=3.4 MPIRUN= FIPY_SOLVERS=scipy
  # - TRAVIS_PYTHON_VERSION=3.5 MPIRUN= FIPY_SOLVERS=scipy

before_install:
  - if [[ $TRAVIS_OS_NAME -eq "linux" ]]; then
      sudo apt-get update;
    fi
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - PY3K=$(echo "$TRAVIS_PYTHON_VERSION >= 3.0" | bc)
  - if [[ $TRAVIS_OS_NAME -eq "linux" ]]; then
      export MINICONDA_OS_NAME=Linux;
    elif [[ $TRAVIS_OS_NAME -eq "osx" ]]; then
      export MINICONDA_OS_NAME=MacOSX;
    fi
  - if [[ $PY3K -eq 1 ]]; then
      export MINICONDA_VERSION=3;
    else
      export MINICONDA_VERSION=;
    fi
  - wget https://repo.continuum.io/miniconda/Miniconda${MINICONDA_VERSION}-latest-${MINICONDA_OS_NAME}-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment
  # stipulate numpy 1.9 because mayavi hasn't been built for 1.10 and 
  # doesn't have a public conda recipe
  - conda install --channel guyer numpy==1.9 nomkl pip gmsh
  - if [[ $PY3K -eq 0 ]]; then
      conda install --channel guyer numpy==1.9 nomkl pysparse mayavi libgfortran openmpi trilinos mpi4py;
    fi
  # Useful for debugging any issues with conda
  - conda info -a
  # - pip install scikit-fmm

install:
  - if [[ $PY3K -eq 1 ]]; then
      2to3 --write . &> /dev/null;
      2to3 --write --doctests_only . &> /dev/null;
    fi
  - cd fipy
  - python setup.py install
  - cd ..

before_script:
  # lack of display causes tests to abort at VtkViewer
  # Workaround @ http://docs.enthought.com/mayavi/mayavi/tips.html#rendering-using-the-virtual-framebuffer
  # and https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
  - if [[ $TRAVIS_OS_NAME -eq "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

notifications:
    email: false

script:
    - ./run_benchmarks.sh

after_script:
    - for d in {periodic,no-flux,T-shape}; do cat $d/meta.yml; echo; done
